---
title: Obtaining sufficient conditions in QCA minimizing the truth table using R
author: Jose M Sallan
date: '2021-10-18'
slug: obtaining-sufficient-conditions-in-qca-minimizing-the-truth-table-using-r
categories:
  - R
tags:
  - QCA
meta_img: images/image.png
description: Description for the page
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>


<p><strong>Qualitative comparative analysis (QCA)</strong> is a data analysis technique that examines the relationships between an outcome and a set of explanatory variables using Boolean algebra, rather than analysis of correlation or covariance structures. Unlike other techniques like linear regression, QCA is focused mainly on examining complex combinations of explanatory variables as antecedents of the outcome.</p>
<p>The aim of most QCA analysis is to find the sufficient conditions for the outcome. In this post, I will introduce the exploration of sufficient conditions with the truth table, and its minimization through the Quine-McCluskey algorithm in the fuzzy-set QCA (fsQCA). I will be using using the <code>QCA</code> package for QCA analysis.</p>
<pre class="r"><code>library(QCA)</code></pre>
<p>Along this post, I will be using the fuzzy-set version of Lipset’s (1959) indicators for the survival of democracy during the inter-war period, included in the <code>QCA</code> package.</p>
<pre class="r"><code>head(LF)</code></pre>
<pre><code>##     DEV  URB  LIT  IND  STB SURV
## AU 0.81 0.12 0.99 0.73 0.43 0.05
## BE 0.99 0.89 0.98 1.00 0.98 0.95
## CZ 0.58 0.98 0.98 0.90 0.91 0.89
## EE 0.16 0.07 0.98 0.01 0.91 0.12
## FI 0.58 0.03 0.99 0.08 0.58 0.77
## FR 0.98 0.03 0.99 0.81 0.95 0.95</code></pre>
<p>In QCA, we use the truth table analysis to find all the sufficient conditions. The analysis is carried out in two steps:</p>
<ul>
<li>First, we construct the <strong>truth table</strong> assigning each case to a combination of observable variables and an outcome.</li>
<li>Second, we simplify the conditions where the outcome is observed with a <strong>logical minimization</strong> process using the Quine-McCluskey algorithm.</li>
</ul>
<p>As a result, we obtain a set of conditions related to the outcome as a simplified sum of products, where the product is the logical AND and the sum the logical OR. This sum of products can be also obtained for the negated outcome. A sample of exemplary research about obtaining sufficient conditions in QCA can be found at Fiss (2011).</p>
<div id="constructing-the-truth-table" class="section level2">
<h2>Constructing the truth table</h2>
<p>In the context of QCA, the truth table contains all possible combinations of AND logical expressions that can take the explanatory variables and its negations. For the LF dataset we have five variables, so we have <span class="math inline">\(2^5 = 32\)</span> different rows. For instance, the expression:</p>
<p><span class="math display">\[DEV* \sim URB * \sim LIT* IND * STB\]</span></p>
<p>corresponds with the row of the truth table:</p>
<pre><code>##   DEV URB LIT IND STB
## 1   1   0   0   1   1</code></pre>
<p>We start assigning each case to a row of the truth table. This is straightforward for a crisp set, as each case has values zero or one for each variable. In fuzzy set QCA (fsQCA) we assing each case to a row of the truth table dychotomizing fuzzy scores: we set to one fuzzy scores greater than 0.5 and to zero scores lower than 0.5. We must take care that in the calibration process no fuzzy score is exactly equal to 0.5. This simple rule assigns each case to its closest row of the truth table. For instance, the case:</p>
<pre><code>##     DEV  URB  LIT  IND  STB SURV
## AU 0.81 0.12 0.99 0.73 0.43 0.05</code></pre>
<p>is included in the row of the truth table:</p>
<pre><code>##   DEV URB LIT IND STB
## 1   1   0   1   1   0</code></pre>
<p>We are not including <code>SURV</code> here, as it is the outcome variable.</p>
<p>As the number of possible combinations of the truth table can be larger than the number of cases, only a subset of rows of the truth table will be present in the sample. Sometimes we might want to exclude rows with a number of cases <code>n</code> too small.</p>
<p>The second step is to assign each row to a value of the outcome, either one or zero. For doing that, we need to specify an <strong>inclusion cut-off</strong>. Rows with a consistency score for sufficient condition above the score will be assigned to the outcome, and the other rows to the negated outcome.</p>
<p>Let’s see how can we obtain the truth table for the <code>LF</code> dataset with an inclusion cut-off of 0.8:</p>
<pre class="r"><code>truthTable(LF, outcome = &quot;SURV&quot;, conditions = &quot;DEV, URB, LIT, IND, STB&quot;, complete = TRUE, show.cases = TRUE, incl.cut = 0.8)</code></pre>
<pre><code>## 
##   OUT: output value
##     n: number of cases in configuration
##  incl: sufficiency inclusion score
##   PRI: proportional reduction in inconsistency
## 
##      DEV URB LIT IND STB   OUT    n  incl  PRI   cases      
##  1    0   0   0   0   0     0     3  0.216 0.000 GR,PT,ES   
##  2    0   0   0   0   1     0     2  0.278 0.000 IT,RO      
##  3    0   0   0   1   0     ?     0    -     -              
##  4    0   0   0   1   1     ?     0    -     -              
##  5    0   0   1   0   0     0     2  0.521 0.113 HU,PL      
##  6    0   0   1   0   1     0     1  0.529 0.228 EE         
##  7    0   0   1   1   0     ?     0    -     -              
##  8    0   0   1   1   1     ?     0    -     -              
##  9    0   1   0   0   0     ?     0    -     -              
## 10    0   1   0   0   1     ?     0    -     -              
## 11    0   1   0   1   0     ?     0    -     -              
## 12    0   1   0   1   1     ?     0    -     -              
## 13    0   1   1   0   0     ?     0    -     -              
## 14    0   1   1   0   1     ?     0    -     -              
## 15    0   1   1   1   0     ?     0    -     -              
## 16    0   1   1   1   1     ?     0    -     -              
## 17    1   0   0   0   0     ?     0    -     -              
## 18    1   0   0   0   1     ?     0    -     -              
## 19    1   0   0   1   0     ?     0    -     -              
## 20    1   0   0   1   1     ?     0    -     -              
## 21    1   0   1   0   0     ?     0    -     -              
## 22    1   0   1   0   1     1     2  0.804 0.719 FI,IE      
## 23    1   0   1   1   0     0     1  0.378 0.040 AU         
## 24    1   0   1   1   1     0     2  0.709 0.634 FR,SE      
## 25    1   1   0   0   0     ?     0    -     -              
## 26    1   1   0   0   1     ?     0    -     -              
## 27    1   1   0   1   0     ?     0    -     -              
## 28    1   1   0   1   1     ?     0    -     -              
## 29    1   1   1   0   0     ?     0    -     -              
## 30    1   1   1   0   1     ?     0    -     -              
## 31    1   1   1   1   0     0     1  0.445 0.050 DE         
## 32    1   1   1   1   1     1     4  0.904 0.886 BE,CZ,NL,UK</code></pre>
<p>We have used <code>complete = TRUE</code> to show all rows Rows without observations (or below the minimal value of observations, that we can specify with <code>n.cut</code>) are <strong>remainders</strong> and have as outcome <code>?</code>.</p>
<p>If we want to see only the rows with consistency above <code>incl.cut</code> and number of cases greater or equal than <code>n.cut</code>, we use the default <code>complete = FALSE</code>:</p>
<pre class="r"><code>truthTable(LF, outcome = &quot;SURV&quot;, conditions = &quot;DEV, URB, LIT, IND, STB&quot;, complete = FALSE, show.cases = TRUE, incl.cut = 0.8)</code></pre>
<pre><code>## 
##   OUT: output value
##     n: number of cases in configuration
##  incl: sufficiency inclusion score
##   PRI: proportional reduction in inconsistency
## 
##      DEV URB LIT IND STB   OUT    n  incl  PRI   cases      
##  1    0   0   0   0   0     0     3  0.216 0.000 GR,PT,ES   
##  2    0   0   0   0   1     0     2  0.278 0.000 IT,RO      
##  5    0   0   1   0   0     0     2  0.521 0.113 HU,PL      
##  6    0   0   1   0   1     0     1  0.529 0.228 EE         
## 22    1   0   1   0   1     1     2  0.804 0.719 FI,IE      
## 23    1   0   1   1   0     0     1  0.378 0.040 AU         
## 24    1   0   1   1   1     0     2  0.709 0.634 FR,SE      
## 31    1   1   1   1   0     0     1  0.445 0.050 DE         
## 32    1   1   1   1   1     1     4  0.904 0.886 BE,CZ,NL,UK</code></pre>
<p>Rows 22 and 32 are associated to <code>OUT = 1</code>, and rows 1, 2, 5, 6, 23, 24 and 31 to <code>OUT = 0</code>. If we set as outcome <code>~SURV</code> instead of <code>SURV</code> we should observe reversed values of <code>OUT</code> for each row. Let’s check that:</p>
<pre class="r"><code>truthTable(LF, outcome = &quot;~SURV&quot;, conditions = &quot;DEV, URB, LIT, IND, STB&quot;, complete = FALSE, show.cases = TRUE, incl.cut = 0.8)</code></pre>
<pre><code>## 
##   OUT: output value
##     n: number of cases in configuration
##  incl: sufficiency inclusion score
##   PRI: proportional reduction in inconsistency
## 
##      DEV URB LIT IND STB   OUT    n  incl  PRI   cases      
##  1    0   0   0   0   0     1     3  1.000 1.000 GR,PT,ES   
##  2    0   0   0   0   1     1     2  0.982 0.975 IT,RO      
##  5    0   0   1   0   0     1     2  0.855 0.732 HU,PL      
##  6    0   0   1   0   1     1     1  0.861 0.772 EE         
## 22    1   0   1   0   1     0     2  0.498 0.281 FI,IE      
## 23    1   0   1   1   0     1     1  0.974 0.960 AU         
## 24    1   0   1   1   1     0     2  0.495 0.366 FR,SE      
## 31    1   1   1   1   0     1     1  0.971 0.950 DE         
## 32    1   1   1   1   1     0     4  0.250 0.106 BE,CZ,NL,UK</code></pre>
<p>Row 24 has <code>OUT = 0</code> for <code>SURV</code> and for <code>~SURV</code>. This is a contradiction. The consistency of this set is too low for both outcomes: 0.709 for <code>SURV</code> and 0.366 for <code>~SURV</code>:</p>
<pre class="r"><code>pof(setms = &quot;DEV*~URB*LIT*IND*STB&quot;, outcome = &quot;SURV&quot;, data = LF, relation = &quot;sufficiency&quot;)</code></pre>
<pre><code>## 
##                          inclS   PRI   covS   covU  
## --------------------------------------------------- 
## 1  DEV*~URB*LIT*IND*STB  0.709  0.634  0.237    -   
## ---------------------------------------------------</code></pre>
<pre class="r"><code>pof(setms = &quot;DEV*~URB*LIT*IND*STB&quot;, outcome = &quot;~SURV&quot;, data = LF, relation = &quot;sufficiency&quot;)</code></pre>
<pre><code>## 
##                          inclS   PRI   covS   covU  
## --------------------------------------------------- 
## 1  DEV*~URB*LIT*IND*STB  0.495  0.366  0.149    -   
## ---------------------------------------------------</code></pre>
<p>To account for that, we can specify an upper and lower bound for consistency passing a vector of two components in <code>incl.cut</code>. Values of consistency within these values will be labelled as contradictory. Here we are making <code>OUT = 1</code> conditions with consistency above 0.8, and <code>OUT = 0</code> consistencies below 0.6. Then, row 24 appears as contradictory <code>OUT = C</code>.</p>
<pre class="r"><code>truthTable(LF, outcome = &quot;SURV&quot;, conditions = &quot;DEV, URB, LIT, IND, STB&quot;, show.cases = TRUE, incl.cut = c(0.8, 0.6))</code></pre>
<pre><code>## 
##   OUT: output value
##     n: number of cases in configuration
##  incl: sufficiency inclusion score
##   PRI: proportional reduction in inconsistency
## 
##      DEV URB LIT IND STB   OUT    n  incl  PRI   cases      
##  1    0   0   0   0   0     0     3  0.216 0.000 GR,PT,ES   
##  2    0   0   0   0   1     0     2  0.278 0.000 IT,RO      
##  5    0   0   1   0   0     0     2  0.521 0.113 HU,PL      
##  6    0   0   1   0   1     0     1  0.529 0.228 EE         
## 22    1   0   1   0   1     1     2  0.804 0.719 FI,IE      
## 23    1   0   1   1   0     0     1  0.378 0.040 AU         
## 24    1   0   1   1   1     C     2  0.709 0.634 FR,SE      
## 31    1   1   1   1   0     0     1  0.445 0.050 DE         
## 32    1   1   1   1   1     1     4  0.904 0.886 BE,CZ,NL,UK</code></pre>
<p>The sufficient conditions for the outcome will be the rows of the truth table with <code>OUT = 1</code>. In this case, these are rows 22 and 32:</p>
<p><span class="math display">\[ DEV * \sim URB * LIT * \sim IND * STB + DEV * URB * LIT * IND * STB  \]</span></p>
</div>
<div id="logical-minimization-of-sufficient-conditions" class="section level2">
<h2>Logical minimization of sufficient conditions</h2>
<p>It is possible that the sufficient conditions for an outcome obtained from the truth table can be made simpler, taking advantage of the following theorem of Boolean algebra:</p>
<p><span class="math display">\[ A*B + A*\sim B = A * \left(B + \sim B \right) = A  \]</span></p>
<p>We can use the Quine-McCluskey algorithm to simplify a logical expression. This algorithm proceeds iteratively, looking in each iteration for expressions that differ only in one element and simplifying them, until no further minimization is possible. The solution resulting from this process is the <strong>conservative solution</strong>. Let’s obtain this solution for our example using the <code>minimize</code> function. I am storing the truth table to minimize in a variable <code>tt</code> for clarity:</p>
<pre class="r"><code>tt &lt;- truthTable(LF, outcome = &quot;SURV&quot;, conditions = &quot;DEV, URB, LIT, IND, STB&quot;, incl.cut = c(0.8, 0.6))
minimize(tt, details = TRUE, show.cases = TRUE)</code></pre>
<pre><code>## 
## M1: DEV*URB*LIT*IND*STB + DEV*~URB*LIT*~IND*STB -&gt; SURV
## 
##                           inclS   PRI   covS   covU   cases 
## ----------------------------------------------------------------- 
## 1    DEV*URB*LIT*IND*STB  0.904  0.886  0.454  0.393  BE,CZ,NL,UK 
## 2  DEV*~URB*LIT*~IND*STB  0.804  0.719  0.265  0.204  FI,IE 
## ----------------------------------------------------------------- 
##                       M1  0.870  0.843  0.658</code></pre>
<p>For this particular case, no minimization has been possible, as the two products differ in two variables.</p>
<p>In this table, we obtain:</p>
<ul>
<li>The obtained solution M1 as sum of products expression.</li>
<li>The consistency, proportional reduction of inconsistency (PRI), raw and unique coverage for each product.</li>
<li>The consistency, PRI and coverage of M1.</li>
<li>The cases attached to each product.</li>
</ul>
<p>We can obtain a similar solution for the negated outcome:</p>
<pre class="r"><code>tt_neg &lt;- truthTable(LF, outcome = &quot;~SURV&quot;, conditions = &quot;DEV, URB, LIT, IND, STB&quot;, incl.cut = c(0.8, 0.6))
minimize(tt_neg, details = TRUE, show.cases = TRUE)</code></pre>
<pre><code>## 
## M1: ~DEV*~URB*~IND + DEV*LIT*IND*~STB -&gt; ~SURV
## 
##                      inclS   PRI   covS   covU   cases 
## --------------------------------------------------------------------------- 
## 1    ~DEV*~URB*~IND  0.886  0.854  0.678  0.582  GR,PT,ES; IT,RO; HU,PL; EE 
## 2  DEV*LIT*IND*~STB  0.981  0.973  0.220  0.124  AU; DE 
## --------------------------------------------------------------------------- 
##                  M1  0.897  0.871  0.803</code></pre>
<p>Through the minimization of the truth table, we obtain a sufficient solution for the outcome (and for its negation), expressed as a sum of products. The appearance of sum or logical OR in the final expression makes salient the equifinality of the studied phenomenon, as there are several, alternative ways to obtain the outcome.</p>
</div>
<div id="bibliography-and-resources" class="section level2">
<h2>Bibliography and resources</h2>
<ul>
<li>Dușa, Adrian (2021). <em>QCA with R: A Comprehensive Resource.</em> <a href="https://bookdown.org/dusadrian/QCAbook/" class="uri">https://bookdown.org/dusadrian/QCAbook/</a></li>
<li>Fiss, P. C. (2011). Building better causal theories: A fuzzy set approach to typologies in organization research. <em>Academy of management journal</em>, 54(2), 393-420. <a href="https://doi.org/10.5465/amj.2011.60263120" class="uri">https://doi.org/10.5465/amj.2011.60263120</a></li>
<li>Lipset, S. M. (1959). Some Social Requisites of Democracy: Economic Development and Political Legitimacy. <em>American Political Science Review</em>, 53:69-105.</li>
</ul>
<p><em>Built with R 4.1.1 and QCA 3.12</em></p>
</div>
